
{{- if .Values.externalSecret.enabled -}}
{{- $root := . -}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
spec:
  refreshInterval: "{{ .Values.externalSecret.refreshInterval }}"
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore.name  }}
    kind: {{ .Values.externalSecret.secretStore.kind  }}
  dataFrom:
  - extract:
      key: {{ .Values.externalSecret.name }}
  {{- range .Values.externalSecret.additionalExternalSecretsRef }}
  - extract:
      key: {{ . }}
  {{- end }}
{{- end }}